package wrpc-bench:bench;

interface ping {
    ping: func();
}

interface greet {
    greet: func(name: string) -> string;
}

world ping-proxy {
    import ping;
    export ping;
}

world greet-proxy {
    import greet;
    export greet;
}

world handler {
    export ping;
    export greet;
}
