name: build via Nix

inputs:
  package:
    description: package specification to build
    required: true

runs:
  using: composite
  steps:
  - run: nix build -L '.#${{ inputs.package }}'
    shell: bash
  - run: nix run -L --inputs-from . 'nixpkgs#coreutils' -- --coreutils-prog=cp -RLv ./result '${{ inputs.package }}'
    shell: bash
  - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
    with:
      name: ${{ inputs.package }}
      path: ${{ inputs.package }}
