name: build via Nix

inputs:
  package:
    description: package specification to build
    required: true

runs:
  using: composite
  steps:
  - run: nix build -L '.#${{ inputs.package }}'
    shell: bash
  - run: nix run -L --inputs-from . 'nixpkgs-unstable#coreutils' -- --coreutils-prog=cp -RLv ./result '${{ inputs.package }}'
    shell: bash
  - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
    with:
      name: ${{ inputs.package }}
      path: ${{ inputs.package }}
