name: build via Nix

inputs:
  package:
    description: package specification to build
    required: true

runs:
  using: composite
  steps:
  - run: nix build -L '.#${{ inputs.package }}'
    shell: bash
  - run: nix run -L --inputs-from . 'nixpkgs-unstable#coreutils' -- --coreutils-prog=cp -RLv ./result '${{ inputs.package }}'
    shell: bash
  - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
    with:
      name: ${{ inputs.package }}
      path: ${{ inputs.package }}
