package foo:bar;

interface component {
  variant unused-variant {
    %enum(unused-enum),
    %record(unused-record),
  }
  enum unused-enum {
    unused,
  }
  record unused-record {
    x: u32,
  }
  ping: func();
}

world test {
  export component;
}

world runner {
  import component;
}
