[package]
name = "wrpc-test"
version = "0.3.0"
description = "wRPC test utilities"

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["http", "quic", "webtransport", "websockets"]
http = ["dep:http", "dep:hyper", "dep:hyper-util"]
quic = ["dep:quinn"]
webtransport = ["dep:wtransport"]
websockets = ["dep:tokio-websockets"]

[dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
http = { workspace = true, optional = true }
hyper = { workspace = true, features = [
    "client",
    "http2",
    "server",
], optional = true }
hyper-util = { workspace = true, features = ["tokio"], optional = true }
quinn = { workspace = true, features = [
    "log",
    "platform-verifier",
    "ring",
    "runtime-tokio",
    "rustls",
], optional = true }
rcgen = { workspace = true, features = ["crypto", "ring", "zeroize"] }
rustls = { workspace = true, features = ["logging", "ring", "std"] }
tokio = { workspace = true, features = ["net", "process", "rt-multi-thread"] }
tokio-websockets = { workspace = true, features = [
    "client",
    "rand",
    "ring",
    "server",
], optional = true }
tracing = { workspace = true }
wrpc-transport = { workspace = true }
wtransport = { workspace = true, features = [
    "ring",
    "self-signed",
], optional = true }
