// Generated by `wit-bindgen-wrpc-go` 0.1.0. DO NOT EDIT!
package error

import (
	context "context"
	wrpc "github.com/wrpc/wrpc/go"
)

type Error interface {
	// Returns a string that is suitable to assist humans in debugging
	// this error.
	//
	// WARNING: The returned string should not be consumed mechanically!
	// It may change across platforms, hosts, or other implementation
	// details. Parsing this string is a major platform-compatibility
	// hazard.
	ToDebugString(ctx__ context.Context, wrpc__ wrpc.Client) (string, func() error, error)
	Drop(ctx__ context.Context, wrpc__ wrpc.Client) error
}
