name: install Nix

permissions:
  id-token: write
  contents: read

inputs:
  cachixAuthToken:
    description: auth token for https://app.cachix.org/organization/wasmcloud/cache/bytecodealliance

runs:
  using: composite
  steps:
  - uses: DeterminateSystems/determinate-nix-action@v3.7.0
    with:
      extra-conf: |
        accept-flake-config = true

  - uses: cachix/cachix-action@v16
    continue-on-error: true
    with:
      name: bytecodealliance
      authToken: '${{ inputs.cachixAuthToken }}'
