name: install Nix

inputs:
  cachixAuthToken:
    description: auth token for https://app.cachix.org/organization/wasmcloud/cache/wrpc

runs:
  using: composite
  steps:
  - uses: DeterminateSystems/nix-installer-action@v13
    with:
      extra-conf: |
        accept-flake-config = true

  - uses: DeterminateSystems/magic-nix-cache-action@v7

  - uses: cachix/cachix-action@v15
    continue-on-error: true
    with:
      name: bytecodealliance
      authToken: '${{ inputs.cachixAuthToken }}'
