[package]
name = "wasi-keyvalue-component-client"
version = "0.1.0"

authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true, features = ["std"] }
wit-bindgen = { workspace = true, features = ["realloc", "macros"] }
