// Generated by `wit-bindgen-wrpc-go` 0.1.0. DO NOT EDIT!
package handler

import (
	bytes "bytes"
	context "context"
	binary "encoding/binary"
	fmt "fmt"
	wrpc "github.com/wrpc/wrpc/go"
	slog "log/slog"
	math "math"
)

type Handler interface {
	Hello(ctx__ context.Context) (r0__ string, err__ error)
}

func ServeInterface(c wrpc.Client, h Handler) (stop func() error, err error) {
	stops := make([]func() error, 0, 1)
	stop = func() error {
		for _, stop := range stops {
			if err := stop(); err != nil {
				return err
			}
		}
		return nil
	}
	stop0, err := c.Serve("wrpc-examples:hello/handler", "hello", func(ctx context.Context, buffer []byte, tx wrpc.Transmitter, inv wrpc.IncomingInvocation) error {
		slog.DebugContext(ctx, "accepting handshake")
		if err := inv.Accept(ctx, nil); err != nil {
			return fmt.Errorf("failed to complete handshake: %w", err)
		}
		slog.DebugContext(ctx, "calling `wrpc-examples:hello/handler.hello` handler")
		r0, err := h.Hello(ctx)
		if err != nil {
			return fmt.Errorf("failed to handle `wrpc-examples:hello/handler.hello` invocation: %w", err)
		}
		var buf bytes.Buffer
		if err := func(v string, w wrpc.ByteWriter) error {
			n := len(v)
			if n > math.MaxUint32 {
				return fmt.Errorf("string byte length of %d overflows a 32-bit integer", n)
			}
			slog.Debug("writing string byte length", "len", n)
			if err := func(v uint32, w wrpc.ByteWriter) error {
				b := make([]byte, binary.MaxVarintLen32)
				i := binary.PutUvarint(b, uint64(v))
				slog.Debug("writing u32")
				_, err := w.Write(b[:i])
				return err
			}(uint32(n), w); err != nil {
				return fmt.Errorf("failed to write string length of %d: %w", n, err)
			}
			slog.Debug("writing string bytes")
			_, err := w.Write([]byte(v))
			if err != nil {
				return fmt.Errorf("failed to write string bytes: %w", err)
			}
			return nil
		}(r0, &buf); err != nil {
			return fmt.Errorf("failed to write result value 0: %w", err)
		}
		slog.DebugContext(ctx, "transmitting `wrpc-examples:hello/handler.hello` result")
		if err := tx.Transmit(context.Background(), buf.Bytes()); err != nil {
			return fmt.Errorf("failed to transmit result: %w", err)
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("failed to serve `wrpc-examples:hello/handler.hello`: %w", err)
	}
	stops = append(stops, stop0)
	return stop, nil
}
