// Generated by `wit-bindgen-wrpc-go` 0.6.0. DO NOT EDIT!
// server package contains wRPC bindings for `server` world
package server

import (
	exports__wrpc_examples__complex__resources "wrpc.io/examples/go/complex-server/bindings/exports/wrpc_examples/complex/resources"
	wrpc "wrpc.io/go"
)

func Serve(s wrpc.Server, h0 exports__wrpc_examples__complex__resources.Handler) (stop func() error, err error) {
	stops := make([]func() error, 0, 1)
	stop = func() error {
		for _, stop := range stops {
			if err := stop(); err != nil {
				return err
			}
		}
		return nil
	}
	stop0, err := exports__wrpc_examples__complex__resources.ServeInterface(s, h0)
	if err != nil {
		return
	}
	stops = append(stops, stop0)
	stop = func() error {
		if err := stop0(); err != nil {
			return err
		}
		return nil
	}
	return
}
