[package]
name = "wasi-keyvalue-unix-server"
version = "0.1.0"

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true, features = ["std"] }
bytes = { workspace = true }
clap = { workspace = true, features = [
    "color",
    "derive",
    "error-context",
    "help",
    "std",
    "suggestions",
    "usage",
] }
futures = { workspace = true }
tokio = { workspace = true, features = [
    "fs",
    "rt-multi-thread",
    "net",
    "signal",
] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = [
    "ansi",
    "env-filter",
    "fmt",
] }
wrpc-transport = { workspace = true, features = ["net"] }
wrpc-wasi-keyvalue = { workspace = true }
wrpc-wasi-keyvalue-mem = { workspace = true }
