// Generated by `wit-bindgen-wrpc-go` 0.11.0. DO NOT EDIT!
// server package contains wRPC bindings for `server` world
package server

import (
	exports__wasi__keyvalue__store "wrpc.io/examples/go/wasi-keyvalue-server/bindings/exports/wasi/keyvalue/store"
	wrpc "wrpc.io/go"
)

func Serve(s wrpc.Server, h0 exports__wasi__keyvalue__store.Handler) (stop func() error, err error) {
	stops := make([]func() error, 0, 1)
	stop = func() error {
		for _, stop := range stops {
			if err := stop(); err != nil {
				return err
			}
		}
		return nil
	}
	stop0, err := exports__wasi__keyvalue__store.ServeInterface(s, h0)
	if err != nil {
		return
	}
	stops = append(stops, stop0)
	stop = func() error {
		if err := stop0(); err != nil {
			return err
		}
		return nil
	}
	return
}
