[package]
name = "hello-component-client"
version = "0.1.0"

authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
wit-bindgen = { workspace = true, features = ["realloc", "macros"] }
